### ISSUE TITLE
Problem with russian words

### ISSUE THREAD

**Issue by sous-park** [Globox1997/TalkBubbles#21]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.22

### Mod Version

1.0.7

### Describe the Issue

The mod cuts off Russian words, leaving only the last one after the space

![4](https://github.com/Globox1997/TalkBubbles/assets/97919124/f85962f5-aec7-4ab4-9568-dec3416e46c9)

### latest.log

[17:50:18] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.22
[17:50:18] [main/INFO]: Loading 58 mods:
	- cloth-config 11.1.106
	   \-- cloth-basic-math 0.6.1
	- fabric-api 0.90.7+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.12+215bbe9677
	   |-- fabric-block-api-v1 1.0.10+92a0d36777
	   |-- fabric-block-view-api-v2 1.0.0+92a0d36777
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.10+57aed33f77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.3.2+d7b148e077
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.39+ae9f657a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.11+d7b148e077
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.2.0+96dfa95977
	   |-- fabric-loot-tables-v1 1.1.44+9e7660c677
	   |-- fabric-message-api-v1 5.1.8+d7b148e077
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.2+4ee0bc6077
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.2.0+39a511ba77
	   |-- fabric-renderer-indigo 1.5.0+39a511ba77
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.6+d7b148e077
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.2+1bc31aeb77
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabricloader 0.14.22
	- java 17
	- minecraft 1.20.1
	- talkbubbles 1.0.7
[17:50:18] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/sous_park/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[17:50:18] [main/INFO]: Compatibility level set to JAVA_16
[17:50:18] [main/INFO]: Compatibility level set to JAVA_17
[17:50:22] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 106 milliseconds
[17:50:23] [main/WARN]: Unrecognized user type: OFFLINE
[17:50:24] [Render thread/INFO]: Environment: ElyEnvironment[name=ely,authHost=https://authserver.ely.by/auth,accountsHost=https://account.ely.by/api/mojang,sessionHost=https://account.ely.by/api/minecraft/session,servicesHost=https://authserver.ely.by/services]
[17:50:24] [Render thread/INFO]: CAFixer is not available: java.lang.NoClassDefFoundError: com/turikhay/caf/util/Logger
[17:50:24] [Render thread/INFO]: Setting user: Notch
[17:50:24] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[17:50:24] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[17:50:25] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (cloth-config, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-tables-v1, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-networking-v0, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, talkbubbles)
[17:50:25] [Worker-Main-8/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[17:50:26] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[17:50:26] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[17:50:26] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[17:50:26] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on          (Realtek(R) Audio)
[17:50:26] [Render thread/INFO]: Sound engine started
[17:50:26] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[17:50:26] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[17:50:26] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[17:50:26] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[17:50:26] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[17:50:26] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[17:50:26] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[17:50:26] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[17:50:26] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[17:50:27] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[17:50:27] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[17:50:27] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[17:50:27] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[17:50:37] [Render thread/INFO]: Connecting to 192.168.1.52, 58879
[17:50:38] [Downloader 0/WARN]: joinServer failed (com.mojang.authlib.GameProfile@1db914c2[id=b61188d1-2f5b-43ca-94cd-3d3800fc6112,name=Notch,properties={},legacy=false])
com.mojang.authlib.exceptions.InvalidCredentialsException: Invalid access_token.
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:121) ~[authlib-4.0.42.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:108) ~[authlib-4.0.42.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.joinServer(YggdrasilMinecraftSessionService.java:80) ~[authlib-4.0.42.jar:?]
	at net.minecraft.class_635.method_2892(class_635.java:112) ~[client-intermediary.jar:?]
	at net.minecraft.class_635.method_2894(class_635.java:94) ~[client-intermediary.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131) ~[guava-31.1-jre.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74) ~[guava-31.1-jre.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82) ~[guava-31.1-jre.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:50:40] [Render thread/WARN]: Ignoring chat session from sous_park due to missing Services public key
[17:50:40] [Render thread/WARN]: Ignoring chat session from Notch due to missing Services public key
[17:50:41] [Render thread/INFO]: Loaded 2 advancements
[17:51:02] [Render thread/INFO]: [Not Secure] [CHAT] <sous_park>               
[17:52:03] [Render thread/INFO]: [Not Secure] [CHAT] <sous_park> it's a bug
[17:52:46] [Render thread/INFO]: [Not Secure] [CHAT] <sous_park>                                                       
[17:52:59] [Render thread/INFO]: [Not Secure] [CHAT] <sous_park> 123 123
[17:53:16] [Render thread/INFO]: [Not Secure] [CHAT] <sous_park> 123         2
[17:53:25] [Render thread/INFO]: [Not Secure] [CHAT] <sous_park>          
[17:53:34] [Render thread/INFO]: [Not Secure] [CHAT] <sous_park>           2
[17:53:45] [Render thread/INFO]: [Not Secure] [CHAT] <sous_park> 2           2
[17:54:04] [Render thread/INFO]: Stopping!
vice.java:108) ~[authlib-4.0.42.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.hasJoinedServerSpecificUrl(YggdrasilMinecraftSessionService.java:138) ~[authlib-4.0.42.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.lambda$submitConcurrentHasJoinedRequest$0(YggdrasilMinecraftSessionService.java:130) ~[authlib-4.0.42.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:50:39] [User Authenticator #1/WARN]: Failed to verify username but will let them in anyway!
[17:50:39] [Server thread/INFO]: Notch[/192.168.1.52:58899] logged in with entity id 595 at (8.5, 72.0, 8.5)
[17:50:39] [Server thread/INFO]: Notch                     
[17:50:39] [Render thread/INFO]: [System] [CHAT] Notch                     
[17:50:39] [Render thread/WARN]: Ignoring chat session from Notch due to missing Services public key
[17:51:02] [Server thread/INFO]: [Not Secure] <sous_park>               
[17:51:02] [Render thread/INFO]: [CHAT] <sous_park>               
[17:52:03] [Server thread/INFO]: [Not Secure] <sous_park> it's a bug
[17:52:03] [Render thread/INFO]: [CHAT] <sous_park> it's a bug
[17:52:46] [Server thread/INFO]: [Not Secure] <sous_park>                                                       
[17:52:46] [Render thread/INFO]: [CHAT] <sous_park>                                                       
[17:52:59] [Server thread/INFO]: [Not Secure] <sous_park> 123 123
[17:52:59] [Render thread/INFO]: [CHAT] <sous_park> 123 123
[17:53:16] [Server thread/INFO]: [Not Secure] <sous_park> 123         2
[17:53:16] [Render thread/INFO]: [CHAT] <sous_park> 123         2
[17:53:25] [Server thread/INFO]: [Not Secure] <sous_park>          
[17:53:25] [Render thread/INFO]: [CHAT] <sous_park>          
[17:53:34] [Server thread/INFO]: [Not Secure] <sous_park>           2
[17:53:34] [Render thread/INFO]: [CHAT] <sous_park>           2
[17:53:45] [Server thread/INFO]: [Not Secure] <sous_park> 2           2
[17:53:45] [Render thread/INFO]: [CHAT] <sous_park> 2           2
[17:54:00] [Server thread/INFO]: Notch lost connection:           
[17:54:00] [Server thread/INFO]: Notch             
[17:54:00] [Render thread/INFO]: [System] [CHAT] Notch             
[17:54:07] [Server thread/INFO]: sous_park lost connection:           
[17:54:07] [Server thread/INFO]: sous_park             
[17:54:07] [Server thread/INFO]: Stopping singleplayer server as player logged out
[17:54:07] [Server thread/INFO]: Stopping server
[17:54:07] [Server thread/INFO]: Saving players
[17:54:07] [Server thread/INFO]: Saving worlds
[17:54:07] [Server thread/INFO]: Saving chunks for level 'ServerLevel[         ]'/minecraft:overworld
[17:54:07] [Server thread/INFO]: Saving chunks for level 'ServerLevel[         ]'/minecraft:the_end
[17:54:07] [Server thread/INFO]: Saving chunks for level 'ServerLevel[         ]'/minecraft:the_nether
[17:54:07] [Server thread/INFO]: ThreadedAnvilChunkStorage (          (36)): All chunks are saved
[17:54:07] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[17:54:07] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[17:54:07] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved

### Do you use any other mods except the required ones?

no

**Comment by Globox1997** [comment]
Mh that sucks

**Comment by fungoza** [comment]
This is due to the fact that the mod is trying to separate messages by characters that are not in the range "A-Za-z0-9_§" or something like that
